# HOW TO BUILD THIS IMAGE
# $ docker build --progress=plain --platform linux/arm64 -t iuridiniz/arm64v8-xwayland:mantic -f Dockerfile.arm64v8-xwayland .

# HOW TO RUN THIS IMAGE
# $ docker run --rm -it --platform linux/arm64 iuridiniz/arm64v8-xwayland:mantic Xwayland -version

# HOW TO EXPORT THIS IMAGE (ever if dockerd is running with userns-remap) - see https://docs.docker.com/engine/security/userns-remap/
# $ docker rm exportme; docker run --platform linux/arm64 --userns host --name exportme iuridiniz/arm64v8-xwayland:mantic Xwayland -version
# $ docker export exportme -o rootfs-xwayland-mantic.tar; docker rm exportme

FROM arm64v8/ubuntu:mantic AS base

ENV DEBIAN_FRONTEND noninteractive

# install Xwayland
RUN apt-get update && apt-get install --no-install-recommends -y \
    xwayland libegl1 libegl-mesa0 \
    && rm -rf /var/lib/apt/lists/*

# test Xwayland
RUN Xwayland -version

# clean up
RUN \
    apt-get -y --purge autoremove && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb && \
    rm -rf /boot/* && \
    rm -rf /lib/modules/* && \
    rm -rf /tmp/* /var/tmp/* /tmp/* && \
    rm -rf /usr/share/doc/* && \
    rm -rf /var/run /run && \
    mkdir -p /var/run /run && \
    /bin/true
# squash image
FROM scratch
COPY --from=base / /

CMD ["Xwayland", "-version"]